language: php

php:
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: 5.6

sudo: false

services:
  - redis-server

before_script:
  - composer self-update
  - composer install

script:
  - phpunit

after_script:
  - php vendor/bin/php-cs-fixer fix src/ --verbose --dry-run --diff